### ISSUE TITLE
[BUG] AutoETS `predict_quantile` and `predict_interval` fail in sktime 0.17.2

### ISSUE THREAD

**Issue by ngupta23** [sktime/sktime#4587]
**Describe the bug**

AutoETS `predict_quantiles` and `predict_interval` fail in sktime 0.17.2, These were working in 0.17.1. Originally observed when we tried to upgrade pycaret to use sktime 0.17.2 (see: https://github.com/pycaret/pycaret/issues/3523).

**To Reproduce**

```python
!pip install sktime==0.17.2

from sktime.datasets import load_airline
from sktime.forecasting.ets import AutoETS

y = load_airline()
forecaster = AutoETS(auto=True, n_jobs=-1, sp=12)  
forecaster.fit(y)  

# Gives error
y_pred = forecaster.predict_quantiles(fh=[1,2,3])

# Also gives error
y_pred = forecaster.predict_interval(fh=[1,2,3])
```

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-b9df560b190c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 y_pred = forecaster.predict_quantiles(fh=[1,2,3])

4 frames
[/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_base.py](https://localhost:8080/#) in predict_quantiles(self, fh, X, alpha)
    559         # we call the ordinary _predict_quantiles if no looping/vectorization needed
    560         if not self._is_vectorized:
--> 561             quantiles = self._predict_quantiles(fh=fh, X=X_inner, alpha=alpha)
    562         else:
    563             # otherwise we call the vectorized version of predict_quantiles

[/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_base.py](https://localhost:8080/#) in _predict_quantiles(self, fh, X, alpha)
   2077 
   2078                 # compute quantile forecasts corresponding to upper/lower
-> 2079                 pred_a = self._predict_interval(fh=fh, X=X, coverage=[coverage])
   2080                 pred_int = pd.concat([pred_int, pred_a], axis=1)
   2081 

[/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/adapters/_statsmodels.py](https://localhost:8080/#) in _predict_interval(self, fh, X, coverage)
    189         valid_indices = fh.to_absolute(self.cutoff).to_pandas()
    190 
--> 191         prediction_results = self._fitted_forecaster.get_prediction(
    192             start=start, end=end, exog=X
    193         )

[/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/exponential_smoothing/ets.py](https://localhost:8080/#) in get_prediction(self, start, end, dynamic, index, method, simulate_repetitions, **simulate_kwargs)
   2100         """
   2101         return PredictionResultsWrapper(
-> 2102             PredictionResults(
   2103                 self,
   2104                 start,

[/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/exponential_smoothing/ets.py](https://localhost:8080/#) in __init__(self, results, start, end, dynamic, index, method, simulate_repetitions, **simulate_kwargs)
   2296             if ndynamic:
   2297                 sim_results.append(
-> 2298                     results.simulate(
   2299                         ndynamic,
   2300                         anchor=anchor_dynamic,

TypeError: ETSResults.simulate() got an unexpected keyword argument 'exog'
```

**Expected behavior**
This worked in sktime 0.17.1 so the behavior should have continued in 0.17.2

**Versions**

/usr/local/lib/python3.10/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

System:
    python: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
executable: /usr/bin/python3
   machine: Linux-5.15.107+-x86_64-with-glibc2.31

Python dependencies:
          pip: 23.1.2
       sktime: 0.17.2
      sklearn: 1.2.2
        numpy: 1.22.4
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.2.0
  statsmodels: 0.13.5
        numba: 0.56.4
     pmdarima: None
      tsfresh: None
   tensorflow: 2.12.0
tensorflow_probability: 0.19.0

**Comment by fkiraly** [comment]
Thanks for reporting.

Two things to note:

* the `auto=True` case was not covered by tests and the failure was not detected, as the estimator does not have a second test parameter set, see https://github.com/sktime/sktime/issues/3429. On a side note, it would be great if you give us all the parameter sets that you are using, either post them or add them to `get_test_params` in crucial estimators.
* the likely cause is the more stringent reimplementation of the probabilistic interfaces, and the refactor by @yarnabrina here https://github.com/sktime/sktime/pull/4465. While imo this improved robustness a lot, it might have removed a hacky workaround. @yarnabrina, would you be so kind to check whether this is indeed related to #4465?

**Comment by fkiraly** [comment]
I added a PR covering the `auto=True` case here.
It is remarkable that this was not tested - I suppose doing https://github.com/sktime/sktime/issues/3429 is not popular (I have been adding this in a lot of estimators).

As said if you have "special" parameter sets downstream, it would be much appreciated if you could add them as a test parameter set. Of course, in this case, not covering `auto=True` seems like a grave oversight.

**Comment by yarnabrina** [comment]
It is indeed from #4465. Added a PR, please take a look.

**Comment by fkiraly** [comment]
ah, that makes sense. Are you testing using #4588?

**Comment by fkiraly** [comment]
Also, theory confirmed, I suppsoe - the refactor by @yarnabrina did not take into account a pre-existing hacky workaround in the case `auto=True` in `AutoETS`. That is, when the concrete implementations moved into the cleanded up, refactored parent class in #4465, the workaround in `AutoETS` silently dropped as it was removed with the special implementation, and the failure was not detected because it was not covered by tests.

**Comment by ngupta23** [comment]
> On a side note, it would be great if you give us all the parameter sets that you are using, either post them or add them to get_test_params in crucial estimators.

All our hyper-parameters (default + tuning) can be [found here](https://github.com/pycaret/pycaret/blob/7f57794ed7d0ccc12750e45bace22afcbe9be622/pycaret/containers/models/time_series.py#L911). They are not completely predetermined. They are selected based on data characteristics.

**Comment by fkiraly** [comment]
> All our hyper-parameters (default + tuning) can be [found here](https://github.com/pycaret/pycaret/blob/7f57794ed7d0ccc12750e45bace22afcbe9be622/pycaret/containers/models/time_series.py#L911). They are not completely predetermined. They are selected based on data characteristics.

I see, thanks!
Would it be a "good first issue" project to translate them into fixed `sktime` sets to ensure test coverage? The test sets in `sktime` should cover all potential settings in `pycaret`, for optimal safety...

**Comment by ngupta23** [comment]
> Would it be a "good first issue" project to translate them into fixed sktime sets to ensure test coverage? The test sets in sktime should cover all potential settings in pycaret, for optimal safety... 
Happy to write a recipe in a pycaret issue if you think that makes sense.

Not sure I follow completely. So, are you going to write a function in pycaret to extract the sets of hyperparameters used for all models ... and then use that, in sktime test params?

**Comment by fkiraly** [comment]
No, the idea is to open an issue on `pycaret` and ask contributors to manually contributed fixed parameter sets to `sktime` in order to ensure the tests in `sktime` cover all the important cases in `pycaret`.

**Comment by ngupta23** [comment]
Sure, no harm in opening an issue :)

**Comment by fkiraly** [comment]
@ngupta, from the discussion in https://github.com/sktime/sktime/pull/4589, it seems that there is some stochastic behaviour if `auto=True`, coming from `statsmodels`. Could you quickly summarize how often you have tested `AutoETS`, e.g., is it plausible that on 0.17.1 it was passing by chance?

**Comment by ngupta23** [comment]
I only tested it once on GitHub CI (which failed with sktime 0.17.1).
Then I tested it manually to try to get to the root cause and that too failed with sktime 0.17.1. It was never failing with 0.17.0.

**Comment by fkiraly** [comment]
Oh, I see - FYI @yarnabrina, it does not fail on 0.17.0 according to @ngupta23.

@ngupta23, how often did you test on 0.17.0? Once, or 100s of times?

**Comment by yarnabrina** [comment]
I do observe similar behaviour on `v0.17.0` as well, with the code snippet
shared in #4589 (will appreciate if either of you can validate as well).

However, I do notice that it seems to matter if `1` is included in `fh` or
not (directly or indirectly), when `auto` is enabled.

```python3
AutoETS(auto=True, n_jobs=-1, sp=12).fit(y).predict_interval(fh=[2])
```

> ValueError: Shape of passed values is (2, 2), indices imply (1, 2)

```python3
AutoETS(auto=True, n_jobs=-1, sp=12).fit(y).predict_interval(fh=[-2])
```

> ValueError: need at least one array to concatenate

```python3
# works
AutoETS(auto=True, n_jobs=-1, sp=12).fit(y).predict_interval(fh=[-2, 2])
AutoETS(auto=True, n_jobs=-1, sp=12).fit(y).predict_interval(fh=[1, 2])
```

Not sure if it's a unknown bug, known issue or desired behaviour (I hope
not). Admittedly, it's even possible that I am reading too much into this
and it's a pure coincidence and `1` has nothing special about it.

@fkiraly, can you suggest anything here? Not sure how to proceed.

**Comment by fkiraly** [comment]
hm, I see - it could be that it is an instance of the common bug where the fh is "forgotten" - say, we have `fh= [2, 5]`, and the wrapped estimator cannot deal with discontinuous `fh`, so we internally ask for `[1, 2, 3, 4, 5]` and then subset to `[2, 5]`. If the logic is faulty, we might forget about the extending, or the subsetting.

Now, 1 *not* being part of the `fh` is a sufficient condition for the `fh` being discontinuous - that could be the relation?

**Comment by ngupta23** [comment]
> @ngupta23, how often did you test on 0.17.0? Once, or 100s of times? I'm asking because there seems to be some stochasticity to the failure.

This is part of out CI which runs every day, so it has been run many times with pycaret 0.17.0 now. I do have to add that pycaret uses the default setting of AutoETS `auto` which is set to `False`. The example I mentioned in the issue above was picked from the AutoETS docstring and since I was able to recreate the original issue with it (with `simulate`), I did not bother changing `auto=False`.

**Comment by fkiraly** [comment]
@ngupta23, we have also been testing `auto=False` which seemed fine, the problem was with `auto=True`. May I drill down:

* were you ever having any problems with `auto=False`?
* how often have you been testing `AutoETS` with the setting `auto=True`?

(the problem for us was that we did not test `auto=True`, that was a mistake)

**Comment by fkiraly** [comment]
> Sure, no harm in opening an issue :)

Done, @ngupta23, I opened an issue with a "recipe" here:

https://github.com/pycaret/pycaret/issues/3550

**Comment by yarnabrina** [comment]
@fkiraly, it seems to me that the issue raised by @ngupta23 will be fixed satisfactorily by the change in #4589, by passing `exog` argument only when supported. But adding #4588 test case have exposed one more issue (and I don't yet know if it's in `sktime` or in `statsmodels`), which is going cause test failures in quite a few tests.

Can we do this?

1. merge #4588 with failure
2. merge #4589 to fix #4587
3. create new issue for `auto=True` case
4. handle in a new PR linked to that issue

> Now, 1 _not_ being part of the `fh` is a sufficient condition for the `fh` being discontinuous - that could be the relation?

Not sure if discontinuity affects it. This works fine (even after large repetition):

```python3
AutoETS(auto=True, n_jobs=-1, sp=12).fit(y).predict_interval(fh=[-4, -2])
```

And for any number (more than one) of negative values as far as I've tested. This also indicates `1` is not the only issue. May be it is that in-sample prediction is fine, only issue is with out-of sample predictions. But why then it fails for a single negative value I don't know yet.

**Comment by ngupta23** [comment]
> were you ever having any problems with auto=False?

Not with sktime 0.17.0 or below, but we did have it when we switched to sktime 0.17.1.

> how often have you been testing AutoETS with the setting auto=True?

None. We specify hyperparameters related to, level, trend, etc. manually with default `auto=False`.

**Comment by fkiraly** [comment]
ah-hah - so it simply was always broken then?

**Comment by fkiraly** [comment]
> But why then it fails for a single negative value I don't know yet.

Could be an indexing or a plusminus 1 issue, e.g., 0 vs 1.

> Can we do this?

That would result in a test failure on main, so we need to add an exception in #4589 to prevent that, and open a bug report to track (and link to in the comment above the exception). The location is `tests/_config.py`, could you do that in your PR, @yarnabrina?

**Comment by ngupta23** [comment]
Sorry, so many issues/PR's related to this topic. I am posting it here, feel free to add/move this to the relevant issue.

The issue maybe related to https://github.com/statsmodels/statsmodels/issues/8487

**Comment by fkiraly** [comment]
> Sorry, so many issues/PR's related to this topic. I am posting it here, feel free to add/move this to the relevant issue.

Sorry for that, @ngupta23. There are actually two bugs (one likely in `statsmodels`, one in `sktime`), and one instance of missing test coverage, it's more "hygienic" to keep them apart as we'll be fixing them separately. Well, possibly with exception of the `statsmodels` issue, but at least we need to track it.
