### ISSUE TITLE
[BUG] _StatsModelsAdapter passes random_state to statsmodels get_prediction, breaking predict_interval on statsmodels 0.15

### ISSUE THREAD

**Issue by siddharth7113** [sktime/sktime#10968]
**Describe the bug**

`_StatsModelsAdapter._predict_interval` always adds a `random_state` argument when it calls statsmodels `get_prediction`. It adds it for every model, including the ones that do not take it. Most statsmodels models do not take it.

Up to statsmodels 0.14 those models ignored the extra argument and printed a `FutureWarning`,statsmodels 0.15.0, released , raises a `TypeError` instead.

So `predict_interval` and `predict_quantiles` now fail on statsmodels 0.15 for several forecasters.

https://github.com/sktime/sktime/blob/d26be800f423eb273d8a83269a2e9ec6dd524d77/sktime/forecasting/base/adapters/_statsmodels.py#L223-L235

The `hasattr` check always passes, because the base class sets that attribute on every subclass:

https://github.com/sktime/sktime/blob/d26be800f423eb273d8a83269a2e9ec6dd524d77/sktime/forecasting/base/adapters/_statsmodels.py#L40-L44

So sktime sends `random_state` to every statsmodels forecaster, whether the model takes it or not.

This causes code errors in the following ways:

1. **ETS.** `ETSResults.get_prediction` takes `**simulate_kwargs` and passes them on to `ETSResults.simulate`. statsmodels 0.15 renamed that method's `random_state` parameter to `rng`:

   ```python
   # statsmodels 0.14.6, ets.py:1594        # statsmodels 0.15.0, ets.py:1587
   def simulate(                            def simulate(
       self, nsimulations, anchor=None,         self, nsimulations, anchor=None,
       repetitions=1, random_errors=None,       repetitions=1, random_errors=None,
       random_state=None,                       rng=None,
   ):                                       ):
   ```

   which raises `TypeError: ETSResults.simulate() got an unexpected keyword argument 'random_state'`.

   This only hits the ETS models that use the simulated path. Models that are additive throughout use a closed form and still work, see `exact_available = ["ANN", "AAN", "AAdN", "ANA", "AAA", "AAdA"]` in `ets.py`. `AutoETS(auto=True)` picks `MAM` on the airline data, so the default path does break.

2. **State space models.** `SARIMAX`, `StatsModelsARIMA` and `UnobservedComponents` never used the argument at all. They take `**kwargs` and used to drop the ones they did not know. statsmodels 0.15 rejects them instead, which raises `TypeError: Unknown keyword arguments: ['random_state']`.

**To Reproduce**

```python
import warnings

warnings.filterwarnings("ignore")

from sktime.datasets import load_airline
from sktime.forecasting.arima import StatsModelsARIMA
from sktime.forecasting.ets import AutoETS
from sktime.forecasting.sarimax import SARIMAX
from sktime.forecasting.structural import UnobservedComponents

y = load_airline()

cases = [
    ("AutoETS(auto=True)", AutoETS(auto=True, sp=12, n_jobs=1)),
    ("AutoETS(MAM)", AutoETS(auto=False, error="mul", trend="add", seasonal="mul", sp=12)),
    ("AutoETS(AAA)", AutoETS(auto=False, error="add", trend="add", seasonal="add", sp=12)),
    ("SARIMAX", SARIMAX(order=(1, 0, 0))),
    ("StatsModelsARIMA", StatsModelsARIMA(order=(1, 0, 0))),
    ("UnobservedComponents", UnobservedComponents(level="local level")),
]

for name, f in cases:
    try:
        f.fit(y)
        f.predict_interval(fh=[1, 2, 3], coverage=[0.9])
        print(f"OK   {name}")
    except TypeError as e:
        print(f"FAIL {name}: {e}")
```

On statsmodels 0.15.0:

```
FAIL AutoETS(auto=True): ETSResults.simulate() got an unexpected keyword argument 'random_state'
FAIL AutoETS(MAM): ETSResults.simulate() got an unexpected keyword argument 'random_state'
OK   AutoETS(AAA)
FAIL SARIMAX: Unknown keyword arguments: ['random_state'].
FAIL StatsModelsARIMA: Unknown keyword arguments: ['random_state'].
FAIL UnobservedComponents: Unknown keyword arguments: ['random_state'].
```

On statsmodels 0.14.6 the same script works, but statsmodels prints this warning for the three state space models:

```
FutureWarning: Unknown keyword arguments: dict_keys(['random_state']).
Passing unknown keyword arguments will raise a TypeError beginning in version 0.15.
```

**Expected behavior**

`predict_interval` and `predict_quantiles` should work on statsmodels 0.15 for all six. sktime should send `random_state` only to the models that use it, and should use the name the installed statsmodels expects.

**Comment by aryamanDutta** [comment]
@siddharth7113 I’d be happy to work on this issue.

The failure appears to come from _StatsModelsAdapter._predict_interval unconditionally forwarding random_state to the underlying statsmodels get_prediction call. This was tolerated by statsmodels <=0.14, but statsmodels 0.15 now raises TypeError for models whose get_prediction signature does not accept that argument.

I’ll investigate the adapter’s prediction-argument forwarding and update it so that random_state is only passed when the underlying statsmodels model actually supports it, while preserving the existing handling of exog and other prediction arguments.

I’ll reproduce the reported failures against statsmodels 0.15, verify the affected ETS and state-space forecasters, and run the relevant prediction-interval/quantile regression tests to ensure the compatibility change does not alter behaviour for models that do accept random_state.
