### PR TITLE
[MNT] remove top level import of transformers

### PR DESCRIPTION
**Pull request by yarnabrina**
Addressing the CI failures observed in #7488

> RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback): cannot import name 'EncoderDecoderCache' from 'transformers' (/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/transformers/init.py)

### CODE REVIEW

**Comment by yarnabrina** [comment]
FYI @benHeid @geetu040 

FYI @fkiraly : if this works, this may be required before next release. Whether the patch release needs to be affected by this or not I am not sure.

There are more than 100 cases of top module level conditional imports of different packages throughout the codebase, not sure whether that is right and/or how to address that.

**Comment by fkiraly** [comment]
I would say, let´s fix it for `transformers` right now only, and then:

* raise an issue
* come up with a programmatic way to test - e.g., installing intentionally empty packages and ensuring that `test-nosoftdeps` or similar passes under that condition

**Comment by yarnabrina** [comment]
@fkiraly https://github.com/sktime/sktime/issues/7492 is created to track the issue, and as of now the failures seem to be from 2 test case failures from `HFTransformersForecaster`. These are generated from `from peft import LoraConfig` inside `get_test_params` of `HFTransformersForecaster`.

**Review by fkiraly — APPROVED** [review]
