### ISSUE TITLE
[BUG] KNeighborsTimeSeriesClassifier.neighbor() failed

### ISSUE THREAD

**Issue by Z-Fran** [sktime/sktime#6515]
**Describe the bug**
The bug was found when I ran https://github.com/sktime/sktime/blob/main/sktime/classification/distance_based/tests/test_time_series_neighbors.py#L127-L147

If setting `algorithm='brute'`, it runs well.
```python
kntsc = KNeighborsTimeSeriesClassifier(n_neighbors=1, algorithm='brute')
kntsc.fit(Xtrain, ytrain)
ret = kntsc.kneighbors(Xtest)
```
But if setting `algorithm='ball_tree'`, it will fail.
```python
kntsc = KNeighborsTimeSeriesClassifier(n_neighbors=1, algorithm='ball_tree')
kntsc.fit(Xtrain, ytrain)
ret = kntsc.kneighbors(Xtest)
```
```
Traceback (most recent call last):
  File "sktime\sktime\classification\distance_based\tests\test_time_series_neighbors.py", line 149, in <module>
    test_knn_kneighbors()
  File "sktime\sktime\classification\distance_based\tests\test_time_series_neighbors.py", line 139, in test_knn_kneighbors
    ret = kntsc.kneighbors(Xtest)
  File "sktime\sktime\distances\adapters\sklearn.py", line 131, in kneighbors
    dist_mat = self._distance(X, self._X)
AttributeError: 'KNeighborsTimeSeriesClassifier' object has no attribute '_X'
```

This is because it runs different `_fit` functions when setting different algorithms. [_fit_precomp](https://github.com/sktime/sktime/blob/main/sktime/classification/distance_based/_time_series_neighbors.py#L341-L344) runs `self._X = X` but [_fit_dist](https://github.com/sktime/sktime/blob/main/sktime/classification/distance_based/_time_series_neighbors.py#L310) not.

In fact, it's caused by #5937

I'm not clear about if this is a mistake or we shouldn't run `KNeighborsTimeSeriesClassifier.neighbor` when setting `algorithm='ball_tree'`.

**Comment by fkiraly** [comment]
It does seem like a bug.

Why was this not caught before? Test case coverage?

**Comment by Z-Fran** [comment]
> Why was this not caught before? Test case coverage?

Yes. The test case only tests the situation `algorithm='brute'`

**Comment by Z-Fran** [comment]
Moreover, if I add a line `self._X = X` to fix it, a new error happens:
```
Traceback (most recent call last):                                                                                                                
  File "C:\Users\Francis\Desktop\sktime\sktime\classification\distance_based\tests\test_time_series_neighbors.py", line 149, in <module>
    test_knn_kneighbors()
  File "sktime\sktime\classification\distance_based\tests\test_time_series_neighbors.py", line 139, in test_knn_kneighbors
    ret = kntsc.kneighbors(Xtest)
  File "sktime\sktime\base\_panel\knn.py", line 67, in kneighbors
    result = self.knn_estimator_.kneighbors(
  File "E:\Anaconda3\envs\sktime\lib\site-packages\sklearn\neighbors\_base.py", line 826, in kneighbors
    X = self._validate_data(X, accept_sparse="csr", reset=False, order="C")
  File "E:\Anaconda3\envs\sktime\lib\site-packages\sklearn\base.py", line 654, in _validate_data
    self._check_n_features(X, reset=reset)
  File "E:\Anaconda3\envs\sktime\lib\site-packages\sklearn\base.py", line 443, in _check_n_features
    raise ValueError(
ValueError: X has 3 features, but KNeighborsClassifier is expecting 36 features as input.
```

**Comment by fkiraly** [comment]
summarizing discussion in mentoring meeting:

* the current code only works for precomputed case
* for brute etc case, passing a precomputed matrix (calling `self._X`) will not work!
* instead, we have to use `_SklearnDistMixin` and `_convert_X_to_sklearn`, in some way
* there should be a case distinction between the brute and the other cases, like in fit/predict
* we also need to add tests for `kneighbors` under various conditions, especially for the brute and other strategies

**Comment by melinny** [comment]
There wasn't a reproducible example above, but I believe this is minimally reproducible example:

```python

from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier
from sktime.datasets import load_italy_power_demand

# data should be split into train/test
X_train, y_train = load_italy_power_demand(split="train", return_type="numpy3D")
X_test, y_test = load_italy_power_demand(split="test", return_type="numpy3D")

from sktime.dists_kernels import FlatDist, ScipyDist

eucl_dist = FlatDist(ScipyDist())
clf = KNeighborsTimeSeriesClassifier(n_neighbors=1, distance=eucl_dist, algorithm='ball_tree')

clf.fit(X_train, y_train)
ret = clf.kneighbors(X_test)
```
