### PR TITLE
[BUG] in `_StatsModelsAdapter`, avoid passing `exog` to `get_prediction` of `statsmodels` in `_predict_interval` if parameter is not supported

### LINKED ISSUE #4587: [BUG] AutoETS `predict_quantile` and `predict_interval` fail in sktime 0.17.2
**Describe the bug**

AutoETS `predict_quantiles` and `predict_interval` fail in sktime 0.17.2, These were working in 0.17.1. Originally observed when we tried to upgrade pycaret to use sktime 0.17.2 (see: https://github.com/pycaret/pycaret/issues/3523).

**To Reproduce**

```python
!pip install sktime==0.17.2

from sktime.datasets import load_airline
from sktime.forecasting.ets import AutoETS

y = load_airline()
forecaster = AutoETS(auto=True, n_jobs=-1, sp=12)  
forecaster.fit(y)  

# Gives error
y_pred = forecaster.predict_quantiles(fh=[1,2,3])

# Also gives error
y_pred = forecaster.predict_interval(fh=[1,2,3])
```

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-b9df560b190c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 y_pred = forecaster.predict_quantiles(fh=[1,2,3])

4 frames
[/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_base.py](https://localhost:8080/#) in predict_quantiles(self, fh, X, alpha)
    559         # we call the ordinary _predict_quantiles if no looping/vectorization needed
    560         if not self._is_vectorized:
--> 561             quantiles = self._predict_quantiles(fh=fh, X=X_inner, alpha=alpha)
    562         else:
    563             # otherwise we call the vectorized version of predict_quantiles

[/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/_base.py](https://localhost:8080/#) in _predict_quantiles(self, fh, X, alpha)
   2077 
   2078                 # compute quantile forecasts corresponding to upper/lower
-> 2079                 pred_a = self._predict_interval(fh=fh, X=X, coverage=[coverage])
   2080                 pred_int = pd.concat([pred_int, pred_a], axis=1)
   2081 

[/usr/local/lib/python3.10/dist-packages/sktime/forecasting/base/adapters/_statsmodels.py](https://localhost:8080/#) in _predict_interval(self, fh, X, coverage)
    189         valid_indices = fh.to_absolute(self.cutoff).to_pandas()
    190 
--> 191         prediction_results = self._fitted_forecaster.get_prediction(
    192             start=start, end=end, exog=X
    193         )

[/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/exponential_smoothing/ets.py](https://localhost:8080/#) in get_prediction(self, start, end, dynamic, index, method, simulate_repetitions, **simulate_kwargs)
   2100         """
   2101         return PredictionResultsWrapper(
-> 2102             PredictionResults(
   2103                 self,
   2104                 start,

[/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/exponential_smoothing/ets.py](https://localhost:8080/#) in __init__(self, results, start, end, dynamic, index, method, simulate_repetitions, **simulate_kwargs)
   2296             if ndynamic:
   2297                 sim_results.append(
-> 2298                     results.simulate(
   2299                         ndynamic,
   2300                         anchor=anchor_dynamic,

TypeError: ETSResults.simulate() got an unexpected keyword argument 'exog'
```

**Expected behavior**
This worked in sktime 0.17.1 so the behavior should have continued in 0.17.2

**Versions**

/usr/local/lib/python3.10/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

System:
    python: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
executable: /usr/bin/python3
   machine: Linux-5.15.107+-x86_64-with-glibc2.31

Python dependencies:
          pip: 23.1.2
       sktime: 0.17.2
      sklearn: 1.2.2
        numpy: 1.22.4
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.2.0
  statsmodels: 0.13.5
        numba: 0.56.4
     pmdarima: None
      tsfresh: None
   tensorflow: 2.12.0
tensorflow_probability: 0.19.0

### PR DESCRIPTION
**Pull request by yarnabrina**
Fixes #4587.
Depends on #4588.

Avoid passing exogenous variables to `get_prediction` if it is not supported.

### CODE REVIEW

**Comment by fkiraly** [comment]
something is not quite right here - it's passing data of wrong shape

**Comment by yarnabrina** [comment]
> something is not quite right here - it's passing data of wrong shape

@fkiraly Is there anything random happening in your knowledge that can explain this?

```pycon
❯ python
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sktime.forecasting.ets import AutoETS
>>> from sktime.utils.estimator_checks import check_estimator
>>> check_estimator(AutoETS, fixtures_to_run="test_predict_time_index[AutoETS-1-y:2cols-fh=[2 5]-int-int-
True]")
2023-05-13 22:31:20.648945: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-13 22:31:20.723929: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-13 22:31:20.724547: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-13 22:31:21.850262: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
All tests PASSED!
{'test_predict_time_index[AutoETS-1-y:2cols-fh=[2 5]-int-int-True]': 'PASSED'}
>>> check_estimator(AutoETS, fixtures_to_run="test_predict_time_index[AutoETS-1-y:2cols-fh=[2 5]-int-int-True]")
FAILED: test_predict_time_index[AutoETS-1-y:2cols-fh=[2 5]-int-int-True]
{'test_predict_time_index[AutoETS-1-y:2cols-fh=[2 5]-int-int-True]': ValueError('Shape of passed values is (5, 2), indices imply (4, 2)')}
>>> 
```

**Comment by fkiraly** [comment]
> Is there anything random happening in your knowledge that can explain this?

How odd. My gut feeling would be, undetected side effect.

**Comment by fkiraly** [comment]
That is very weird. Out of 100 runs, 21 pass...

```python
n_pass = 0
for _ in range(100):
    try:
        check_estimator(AutoETS, fixtures_to_run="test_predict_time_index[AutoETS-1-y:2cols-fh=[2 5]-int-int-True]", raise_exceptions=True)
        n_pass = n_pass + 1
    except:
        pass
```

**Comment by fkiraly** [comment]
This seems to be coming from `statmodels`, the `PredictionResults.pred_int` which seems to try construct a `DataFrame` with non-matching indices?

**Comment by yarnabrina** [comment]
> This seems to be coming from `statmodels`, the `PredictionResults.pred_int` which seems to try construct a `DataFrame` with non-matching indices?

Yes, and somehow I don't think it's about #4465 changes any more. It's something to do with `auto` itself.

```python3
from sktime.datasets import load_airline
y = load_airline()

from sktime.forecasting.ets import AutoETS

n_fail = 0
for _ in range(100):
    try:
        AutoETS(sp=12).fit(y).predict_interval(fh=[2])  # always pass
    except Exception:
        n_fail += 1

n_pass = 0
for _ in range(100):
    try:
        AutoETS(auto=True, sp=12).fit(y).predict_interval(fh=[2])  # always fail
    except Exception:
        pass
    else:
        n_pass += 1

print(f"{n_fail=} {n_pass=}")  # n_fail=0 n_pass=0
```

On my local, this happens on both `bugfix-4587` branch and on `v0.17.1` tag, where @ngupta23's code was working previously.

@fkiraly: Will it be possible for you to reproduce it in both old/new codebases? I tried by checking out a new detached head and running there, not sure if there's an easier way.

**Comment by fkiraly** [comment]
> Will it be possible for you to reproduce it in both old/new codebases? 

Sure, reproducing on windows, python 3.10.

On current `main`: `n_fail=0 n_pass=0`

On 0.17.1 release tag: `n_fail=0 n_pass=0`

**Comment by fkiraly** [comment]
@yarnabrina; same confired with 0.17.0

**Comment by yarnabrina** [comment]
@fkiraly any suggestion what's causing this error?

> object.__init__() takes exactly one argument (the instance to initialize)

Is it something to do latest release of `holidays`?

**Comment by fkiraly** [comment]
well, that's new. Holidays in Turkey causing an exception? Seems to propagate through `prophet`.

I'm not coding at the moment but will have a closer look in 1-2 hours - would appreciate issue and/or PR that bounds the suspicious dependency.

**Review by fkiraly — APPROVED** [review]
Fixes it, thanks.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Actually, I'm worried about one thing - we don't cover the fixed logic with tests, because the exceptions in `_config.py` stop the tests that cover the `auto=False` case too.

Should we maybe do the following instead:

* don't change `_config.py`
* comment out `params2`
* add a clear note in the issue tracking the `auto=True` case that `params2` needs to be uncommented in the PR that has the fix?

**Review by fkiraly — APPROVED** [review]
👍
