### PR TITLE
[BUG] Fix `random_state` handling in `statsmodels` adapter

### LINKED ISSUE #10968: [BUG] _StatsModelsAdapter passes random_state to statsmodels get_prediction, breaking predict_interval on statsmodels 0.15
**Describe the bug**

`_StatsModelsAdapter._predict_interval` always adds a `random_state` argument when it calls statsmodels `get_prediction`. It adds it for every model, including the ones that do not take it. Most statsmodels models do not take it.

Up to statsmodels 0.14 those models ignored the extra argument and printed a `FutureWarning`,statsmodels 0.15.0, released , raises a `TypeError` instead.

So `predict_interval` and `predict_quantiles` now fail on statsmodels 0.15 for several forecasters.

https://github.com/sktime/sktime/blob/d26be800f423eb273d8a83269a2e9ec6dd524d77/sktime/forecasting/base/adapters/_statsmodels.py#L223-L235

The `hasattr` check always passes, because the base class sets that attribute on every subclass:

https://github.com/sktime/sktime/blob/d26be800f423eb273d8a83269a2e9ec6dd524d77/sktime/forecasting/base/adapters/_statsmodels.py#L40-L44

So sktime sends `random_state` to every statsmodels forecaster, whether the model takes it or not.

This causes code errors in the following ways:

1. **ETS.** `ETSResults.get_prediction` takes `**simulate_kwargs` and passes them on to `ETSResults.simulate`. statsmodels 0.15 renamed that method's `random_state` parameter to `rng`:

   ```python
   # statsmodels 0.14.6, ets.py:1594        # statsmodels 0.15.0, ets.py:1587
   def simulate(                            def simulate(
       self, nsimulations, anchor=None,         self, nsimulations, anchor=None,
       repetitions=1, random_errors=None,       repetitions=1, random_errors=None,
       random_state=None,                       rng=None,
   ):                                       ):
   ```

   which raises `TypeError: ETSResults.simulate() got an unexpected keyword argument 'random_state'`.

   This only hits the ETS models that use the simulated path. Models that are additive throughout use a closed form and still work, see `exact_available = ["ANN", "AAN", "AAdN", "ANA", "AAA", "AAdA"]` in `ets.py`. `AutoETS(auto=True)` picks `MAM` on the airline data, so the default path does break.

2. **State space models.** `SARIMAX`, `StatsModelsARIMA` and `UnobservedComponents` never used the argument at all. They take `**kwargs` and used to drop the ones they did not know. statsmodels 0.15 rejects them instead, which raises `TypeError: Unknown keyword arguments: ['random_state']`.

**To Reproduce**

```python
import warnings

warnings.filterwarnings("ignore")

from sktime.datasets import load_airline
from sktime.forecasting.arima import StatsModelsARIMA
from sktime.forecasting.ets import AutoETS
from sktime.forecasting.sarimax import SARIMAX
from sktime.forecasting.structural import UnobservedComponents

y = load_airline()

cases = [
    ("AutoETS(auto=True)", AutoETS(auto=True, sp=12, n_jobs=1)),
    ("AutoETS(MAM)", AutoETS(auto=False, error="mul", trend="add", seasonal="mul", sp=12)),
    ("AutoETS(AAA)", AutoETS(auto=False, error="add", trend="add", seasonal="add", sp=12)),
    ("SARIMAX", SARIMAX(order=(1, 0, 0))),
    ("StatsModelsARIMA", StatsModelsARIMA(order=(1, 0, 0))),
    ("UnobservedComponents", UnobservedComponents(level="local level")),
]

for name, f in cases:
    try:
        f.fit(y)
        f.predict_interval(fh=[1, 2, 3], coverage=[0.9])
        print(f"OK   {name}")
    except TypeError as e:
        print(f"FAIL {name}: {e}")
```

On statsmodels 0.15.0:

```
FAIL AutoETS(auto=True): ETSResults.simulate() got an unexpected keyword argument 'random_state'
FAIL AutoETS(MAM): ETSResults.simulate() got an unexpected keyword argument 'random_state'
OK   AutoETS(AAA)
FAIL SARIMAX: Unknown keyword arguments: ['random_state'].
FAIL StatsModelsARIMA: Unknown keyword arguments: ['random_state'].
FAIL UnobservedComponents: Unknown keyword arguments: ['random_state'].
```

On statsmodels 0.14.6 the same script works, but statsmodels prints this warning for the three state space models:

```
FutureWarning: Unknown keyword arguments: dict_keys(['random_state']).
Passing unknown keyword arguments will raise a TypeError beginning in version 0.15.
```

**Expected behavior**

`predict_interval` and `predict_quantiles` should work on statsmodels 0.15 for all six. sktime should send `random_state` only to the models that use it, and should use the name the installed statsmodels expects.

### PR DESCRIPTION
**Pull request by aryamanDutta**
#### Reference Issues/PRs

Fixes #10968.

#### What does this implement/fix? Explain your changes.

`_StatsModelsAdapter._predict_interval` used to pass `random_state` to
`get_prediction` for all statsmodels-based forecasters.

However, this breaks with statsmodels 0.15, since some state-space models
reject the unsupported argument, while ETS models pass simulation arguments
through `simulate_kwargs`, and the `simulate` method now uses `rng` instead
of `random_state`.

This PR:
- only passes `random_state` when it is supported by the underlying
  `get_prediction`;
- for ETS models, passes the random state through `simulate_kwargs`;
- detects whether the underlying `simulate` method expects `rng` or
  `random_state`, preserving compatibility with statsmodels 0.14 and 0.15.

Other than that, the behavior of the forecasting functions is unchanged.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### What should a reviewer concentrate their feedback on?

- Whether the signature-based approach correctly distinguishes the ETS
  `simulate_kwargs` path from other statsmodels models.
- Whether the `rng`/`random_state` handling is correct for the supported
  statsmodels versions.
- Whether the regression test adequately covers the #10968 scenario.

#### Did you add any tests for the change?

Yes.

A regression test for the scenario described in #10968 was added. It verifies
that `random_state` is not passed to `get_prediction` for non-ETS models,
while for ETS models it is passed through `simulate_kwargs`.

The test was run locally and passed. The complete `test_base_bugs.py` test
file also passes:

- `test_base_bugs.py`: 3/3 tests passed
- `test_statsmodels_adapter_random_state_handling`: passed
- pre-commit formatting and linting checks: passed

#### Any other comments?

The fix was also tested locally with statsmodels 0.15 using SARIMAX,
UnobservedComponents, and AutoETS prediction intervals.

No new dependencies were introduced.

### CODE REVIEW

File: sktime/forecasting/base/adapters/_statsmodels.py [hunk 1]
```diff
@@ -222,8 +222,27 @@ def _predict_interval(self, fh, X, coverage):
 
         get_prediction_arguments = {"start": start, "end": end}
 
-        if hasattr(self, "random_state"):
-            get_prediction_arguments["random_state"] = self.random_state
+        # Only pass random_state when supported by get_prediction.
+        if self.random_state is not None:
```
Comment (fkiraly) [inline sktime/forecasting/base/adapters/_statsmodels.py]: I would leave the more conservative if hasattr, but the rest looks good.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Thanks, great!

I am concerned why this is not caught by the tests.

Can you please check `get_test_params` of the ETS estimator, and ensure that there is a parameter set with `random_state` being passed?

File: sktime/forecasting/base/adapters/_statsmodels.py (hunk 1 above)
Comment (aryamanDutta) [reply sktime/forecasting/base/adapters/_statsmodels.py]: yup understood.

**Review by fkiraly — DISMISSED** [review]
Looks good for me now - I restored the old test case which I assume was accidentally overwritten, and added the new one at the end.
