### PR TITLE
[MNT] update sphinx upper bound after skipping 7.2.0

### LINKED ISSUE #5117: [BUG] readthedocs build failing with `AttributeError("'TocTree' object has no attribute 'get_toctree_ancestors'")`
Readthedocs builds are erroring out with `sphinx.errors.ThemeError: An error happened in rendering the page about.
Reason: AttributeError("'TocTree' object has no attribute 'get_toctree_ancestors'")`, since yesterday, I think?

I can identify no immediate reason why they would.

This seems high priority as it prevents us from updating documentation.

### PR DESCRIPTION
**Pull request by yarnabrina**
Closes #5117

### CODE REVIEW

**Comment by AA-Turner** [comment]
[Sphinx 7.2.2](https://pypi.org/project/Sphinx/7.2.2/) has been released, please may you test with the new version?

A

**Comment by yarnabrina** [comment]
Hi @AA-Turner, build using `7.2.2` worked fine, thank you.
