### ISSUE TITLE
[BUG] ForecastingSkoptSearchCV documentation example fails to run

### ISSUE THREAD

**Issue by gareth-brown-86** [sktime/sktime#6507]
**Describe the bug**

The [example](https://sktime-backup.readthedocs.io/en/v0.24.2/api_reference/auto_generated/sktime.forecasting.model_selection.ForecastingSkoptSearchCV.html)  in ForecastingSkoptSearchCV documentation fails with an error
```
TypeError: sktime.forecasting.model_selection._tune._fit_and_score_skopt.<locals>._fit_and_score() argument after ** must be a mapping, not list
```
**To Reproduce**

```python
from sktime.datasets import load_shampoo_sales
from sktime.forecasting.model_selection import ForecastingSkoptSearchCV
from sktime.split import ExpandingWindowSplitter
from sklearn.ensemble import GradientBoostingRegressor
from sktime.forecasting.compose import make_reduction

y = load_shampoo_sales()
fh = [1, 2, 3, 4]
cv = ExpandingWindowSplitter(fh=fh)
forecaster = make_reduction(GradientBoostingRegressor(random_state=10))
param_distributions = {
    "estimator__learning_rate": (1e-4, 1e-1, "log-uniform"),
    "window_length": (1, 10, "uniform"),
    "estimator__criterion": ["friedman_mse", "squared_error"],
}
sscv = ForecastingSkoptSearchCV(
    forecaster=forecaster,
    param_distributions=param_distributions,
    cv=cv,
    n_iter=5,
    random_state=10,
)
sscv.fit(y)
y_pred = sscv.predict(fh)
```

**Expected behavior**

I expected the code to run without error, and to hyper parameter tune the GradientBoostingRegressor
**Additional context**

**Versions**
<details>

System:
    python: 3.11.9 (main, May 28 2024, 14:07:47) [Clang 15.0.0 (clang-1500.3.9.4)]
executable: ~/venv/bin/python
   machine: macOS-14.4.1-arm64-arm-64bit

Python dependencies:
          pip: 24.0
       sktime: 0.29.0
      sklearn: 1.4.2
       skbase: 0.7.8
        numpy: 1.23.5
        scipy: 1.13.1
       pandas: 2.2.2
   matplotlib: None
       joblib: 1.4.2
        numba: None
  statsmodels: None
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by gareth-brown-eon** [comment]
@fnhirwa

**Comment by gareth-brown-eon** [comment]
It looks like the final return and call of _fit_and_score should not have dictionary unpacking is a change from: 

```python
    return _fit_and_score(**params)
```
to:
```python
    return _fit_and_score(params)
```

https://github.com/sktime/sktime/blob/8d7358c32ef9c6c0baed27c2375a21d4ce43edc7/sktime/forecasting/model_selection/_tune.py#L1589

**Comment by fkiraly** [comment]
The main question I have is:

* why do tests not catch this?
* if it fails now, what explains that we merged it and did not see tests failures since then?

**Comment by fkiraly** [comment]
FYI @hazrulakmal

**Comment by gareth-brown-eon** [comment]
> The main question I have is:
> 
>     * why do tests not catch this?
> 
>     * if it fails now, what explains that we merged it and did not see tests failures since then?

Regarding the tests, do you install the dependencies for the test (skopt)? [The test](https://github.com/sktime/sktime/blob/main/sktime/forecasting/model_selection/tests/test_tune.py#L251) seem to have a skip condition is the softdeps are not present:

```python
@pytest.mark.skipif(
    not run_test_for_class(ForecastingSkoptSearchCV),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
```

**Comment by fkiraly** [comment]
Yes, I think they are present in the `all_extras` dependency set, as `scikit-optimize`, see `pyproject.toml`:
https://github.com/sktime/sktime/blob/59ee009ea70cf798cbba01312414f4f19cbdfdfa/pyproject.toml#L102

**Comment by yarnabrina** [comment]
I am not sure if it is the case or not, but when @hazrulakmal added this we were using `0.9.0` of `scikit-optimize` and were pretty convinced that the project has died. It seems that there had been a new release in March 2024 of `0.10.0` and `0.10.1`.

@gareth-brown-eon can I request you to kindly report which version of `scikit-optimize` you are using? If it's the latest release, there may be a chance of behvaiour change in new minor release, so can you please try in the older version too? That'd at least explain why was this not caught earlier during PR.

**Comment by gareth-brown-eon** [comment]
> I am not sure if it is the case or not, but when @hazrulakmal added this we were using `0.9.0` of `scikit-optimize` and were pretty convinced that the project has died. It seems that there had been a new release in March 2024 of `0.10.0` and `0.10.1`.
> 
> @gareth-brown-eon can I request you to kindly report which version of `scikit-optimize` you are using? If it's the latest release, there may be a chance of behvaiour change in new minor release, so can you please try in the older version too? That'd at least explain why was this not caught earlier during PR.

I used scikit-optimize 0.10.1, and have confirmed its on 0.9.0 also.
But I think what is causing the issue is passing the `**params` in the call to the function: `_fit_and_score(**params)` 
Params at this point is a list, so cannot be passed in this way.

I think the main issue now is why the tests are not picking this up

**Comment by fnhirwa** [comment]
@yarnabrina  is there a possibility that tests are not capturing this due to dependency clash?
https://github.com/sktime/sktime/blob/87b94dd41d5d63cd73bd09cb7cf37e6f94b9dcc9/sktime/forecasting/model_selection/_tune.py#L1156

**Comment by gareth-brown-eon** [comment]
> @yarnabrina is there a possibility that tests are not capturing this due to dependency clash?
> 
> https://github.com/sktime/sktime/blob/87b94dd41d5d63cd73bd09cb7cf37e6f94b9dcc9/sktime/forecasting/model_selection/_tune.py#L1156



> @yarnabrina is there a possibility that tests are not capturing this due to dependency clash?
> 
> https://github.com/sktime/sktime/blob/87b94dd41d5d63cd73bd09cb7cf37e6f94b9dcc9/sktime/forecasting/model_selection/_tune.py#L1156

Yeah just running the tests locally with the `return_reason=True` I get 

`ForecastingSkoptSearchCV requires package 'numpy<1.24' to be present in the python environment, with version <1.24, b...`

**Comment by fkiraly** [comment]
I see - at some point `numpy` in the CI moved past 1.24, and from that point the tests were no longer run, since we do not construct environment specific to estimators, but instead run all estimators compatible with selected CI environments.

**Comment by fkiraly** [comment]
Is the `numpy<1.24` bound still accurate for `scikit-optimize`?

**Comment by gareth-brown-86** [comment]
I have just created a new feature branch locally to push the changes into, what I noticed:

- to get the test to run, I needed to downgrade to `numpy<1.24.0` I worked on `numpy==1.23.5`
- I also needed to downgrade scikit-learn to 1.4.2, because on an issue `cannot import name 'check_pandas_support' from 'sklearn.utils'`
- When I then ran the tests, they failed for the issue I saw originally
- When I made the change, (removing the `**`) all tests now passed

**Comment by fnhirwa** [comment]
> Is the `numpy<1.24` bound still accurate for `scikit-optimize`?

I don't think it is an issue as it is indicated that they support `"numpy>=1.12"`
https://github.com/scikit-optimize/scikit-optimize/blob/a2369ddbc332d16d8ff173b12404b03fea472492/pyproject.toml#L6

We could test it from our end to ensure that we solve the dependency issue. But also the `skopt` repo is publicly archived🙄

**Comment by gareth-brown-86** [comment]
> > Is the `numpy<1.24` bound still accurate for `scikit-optimize`?
> 
> I don't think it is an issue as it is indicated that they support `"numpy>=1.12"` https://github.com/scikit-optimize/scikit-optimize/blob/a2369ddbc332d16d8ff173b12404b03fea472492/pyproject.toml#L6
> 
> We could test it from our end to ensure that we solve the dependency issue. But also the `skopt` repo is publicly archived🙄

I have tried removing the requirement on numpy, and all skopt tests still run.

**Comment by fkiraly** [comment]
> I have tried removing the requirement on numpy, and all skopt tests still run.

Have you done so in an environment with a more recent `numpy`? I remember there were some compatibility issues.

Also, is `scikit-optimize` defunct?

**Comment by gareth-brown-86** [comment]
> > I have tried removing the requirement on numpy, and all skopt tests still run.
> 
> Have you done so in an environment with a more recent `numpy`? I remember there were some compatibility issues.
> 
> Also, is `scikit-optimize` defunct?

Yeah I have tried with `numpy==1.26.4`. 

 `scikit-optimize` is now archived.

**Comment by fkiraly** [comment]
Thanks! So, `scikit-optimize` is defunct basically?

Archived on Feb 28? Which makes it impossible to post,
Is the community still alive somewhere, or who is owning it?

As alternatives, good first issue with open requests for interfacing other tuning frameworks, if of interest: https://github.com/sktime/sktime/issues/4188

**Comment by gareth-brown-86** [comment]
> Thanks! So, `scikit-optimize` is defunct basically?
> 
> Archived on Feb 28? Which makes it impossible to post, Is the community still alive somewhere, or who is owning it?
> 
> As alternatives, good first issue with open requests for interfacing other tuning frameworks, if of interest: #4188

I am planning to contribute to the interface to optuna, but am using skopt interface as an example to follow, but when the example didnt work, thought I would fix that before moving on.

**Comment by fkiraly** [comment]
Thanks. It's maybe not the best example, given that the package here has been dying for a while now. Do you know who were the last maintainers of `scikit-optimize`? Would be a shame if it just drops out of maintenance because no one merges dependabots etc.

**Comment by yarnabrina** [comment]
> Thanks! So, `scikit-optimize` is defunct basically?

FYI https://github.com/holgern/scikit-optimize

**Comment by fkiraly** [comment]
Who is @holgern, and is that an official fork?

**Comment by fkiraly** [comment]
I opened an issue here:
https://github.com/holgern/scikit-optimize/issues/6

This situation looks quite strange. What is going on?

**Comment by fkiraly** [comment]
I have opened a separate maintenance issue on tracking `skopt`: https://github.com/sktime/sktime/issues/6527
