### ISSUE TITLE
[BUG] sktime 0.17.1 breaks in-sample `predict_quantiles` in `pmdarima` adapter

### ISSUE THREAD

**Issue by ngupta23** [sktime/sktime#4468]
**Describe the bug**
The latest release of sktime breaks in-sample predictions for ARIMA models

**To Reproduce**

```python
from sktime.datasets import load_airline
from sktime.forecasting.arima import ARIMA

y = load_airline()
forecaster = ARIMA(order=(1, 1, 0), seasonal_order=(0, 1, 0, 12), suppress_warnings=True)
forecaster.fit(y)
forecaster.predict_quantiles(fh=y.index, X=None, alpha=[0.05, 0.95])
```

```python-traceback
'numpy.ndarray' object has no attribute 'to_pandas'
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_17p1\Lib\site-packages\sktime\forecasting\base\adapters\_pmdarima.py", line 169, in _predict_in_sample
    index=fh_abs.to_pandas(), columns=["lower", "upper"]
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_17p1\Lib\site-packages\sktime\forecasting\base\adapters\_pmdarima.py", line 293, in _predict_interval
    _, y_pred_int = self._predict_in_sample(fh_ins, **kwargs)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_17p1\Lib\site-packages\sktime\forecasting\base\_base.py", line 2079, in _predict_quantiles
    pred_a = self._predict_interval(fh=fh, X=X, coverage=[coverage])
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_17p1\Lib\site-packages\sktime\forecasting\base\_base.py", line 559, in predict_quantiles
    quantiles = self._predict_quantiles(fh=fh, X=X_inner, alpha=alpha)
  File "C:\Users\Nikhil\OneDrive\my_libraries\my_python_libraries\pycaret\pycaret_dev\time_series_debug.py", line 28, in <module>
    forecaster.predict_quantiles(fh=y.index, X=None, alpha=[0.05, 0.95])
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_17p1\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_17p1\Lib\runpy.py", line 196, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
AttributeError: 'numpy.ndarray' object has no attribute 'to_pandas'
```

**Expected behavior**
This was working in sktime 0.16.x and also works in 0.17.0

**Additional context**
pycaret tests failing due to sktime 0.17.1 upgrade: https://github.com/pycaret/pycaret/actions/runs/4674814052/jobs/8279339435#logs

**Versions**
<details>
System:
    python: 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_17p1\python.exe
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
          pip: 23.0.1
       sktime: 0.17.1
      sklearn: 1.2.2
        numpy: 1.23.5
        scipy: 1.10.1
       pandas: 1.5.3
   matplotlib: 3.7.1
       joblib: 1.2.0
  statsmodels: 0.13.5
        numba: 0.56.4
     pmdarima: 2.0.3
      tsfresh: None
   tensorflow: None
tensorflow_probability: None
</details>

**Comment by fkiraly** [comment]
Thanks for reporting!

This is a consequence of the `pandas 2` upgrade, and it seems like in-sample predictions of `predict_quantiles` were not tested.

Fix is here, but we will also need to add tests.
https://github.com/sktime/sktime/pull/4469

**Comment by fkiraly** [comment]
FYI @yarnabrina

**Comment by fkiraly** [comment]
@ngupta23, on the bright side, out-of-sample it's `pandas 2` compatible now 😅

**Comment by fkiraly** [comment]
new tests for all proba forecasters in-sample here: https://github.com/sktime/sktime/pull/4470

**Comment by fkiraly** [comment]
also present in `_StatsForecastAdapter` which looks like copy-paste from `_PmdArimaAdapter`
